export const USER_START = "USER_START";
export const USER_FAILD = "USER_FAILD";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FETCH = "USER_FETCH";
export const USER_FETCHED = "USER_FETCHED";
export const USER_INIT = "USER_INIT";
export const USER_PROFILE_IMAGE_START = "USER_PROFILE_IMAGE_START";
export const USER_PROFILE_IMAGE_FAILD = "USER_PROFILE_IMAGE_FAILD";
export const USER_PROFILE_IMAGE_UPLOAD = "USER_PROFILE_IMAGE_UPLOAD";
export const USER_PROFILE_IMAGE_DELETE = "USER_PROFILE_IMAGE_DELETE";
export const USER_PROFILE_IMAGE_SUCCESS = "USER_PROFILE_IMAGE_SUCCESS";

export const USER_FOLLOW = "USER_FOLLOW";
export const USER_UNFOLLOW = "USER_UNFOLLOW";
export const USER_FOLLOW_UNFOLLOW_START = "USER_FOLLOW_UNFOLLOW_START";
export const USER_FOLLOW_UNFOLLOW_UPDATED = "USER_FOLLOW_UNFOLLOW_UPDATED";

export const USER_SEARCH = "USER_SEARCH";
export const USER_SEARCH_START = "USER_SEARCH_START";
export const USER_SEARCH_FAILED = "USER_SEARCH_FAILED";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";

export const USER_SOCIAL_STATS = "USER_SOCIAL_STATS";
export const USER_SOCIAL_STATS_START = "USER_SOCIAL_STATS_START";
export const USER_SOCIAL_STATS_FAILD = "USER_SOCIAL_STATS_FAILD";
export const USER_SOCIAL_STATS_UPDATE = "USER_SOCIAL_STATS_UPDATE";

export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATE_START = "USER_UPDATE_START";
export const USER_STATE_UPDATE = "USER_STATE_UPDATE";
