export const MODAL_ACTION_OPEN = "MODAL_ACTION_OPEN";
export const MODAL_DELETE_OPEN = "MODAL_DELETE_OPEN";
export const MODAL_CREATE_EXIT = "MODAL_CREATE_EXIT";
export const MODAL_CREATE_OPEN = "MODAL_CREATE_OPEN";
export const MODAL_CREATE_CLOSE = "MODAL_CREATE_CLOSE";
export const MODAL_ACTION_CLOSE = "MODAL_ACTION_CLOSE";
export const MODAL_SETTING_OPEN = "MODAL_SETTING_OPEN";
export const MODAL_DELETE_CLOSE = "MODAL_DELETE_CLOSE";
export const MODAL_UNFOLLOW_OPEN = "MODAL_UNFOLLOW_OPEN";
export const MODAL_SETTING_CLOSE = "MODAL_SETTING_CLOSE";
export const MODAL_UNFOLLOW_CLOSE = "MODAL_UNFOLLOW_CLOSE";
export const MODAL_CREATE_UPDATE_FILE = "MODAL_CREATE_UPDATE_FILE";
export const MODAL_CREATE_UPDATE_DISCARD = "MODAL_CREATE_UPDATE_DISCARD";

export const MODAL_SOCIAL_STATS_OPEN = "MODAL_SOCIAL_STATS_OPEN";
export const MODAL_SOCIAL_STATS_CLOSE = "MODAL_SOCIAL_STATS_CLOSE";
export const MODAL_SOCIAL_STATS_FAILD = "MODAL_SOCIAL_STATS_FAILD";
export const MODAL_SOCIAL_STATS_START = "MODAL_SOCIAL_STATS_START";

export const MODAL_PROFILE_UPLOAD_OPEN = "MODAL_PROFILE_UPLOAD_OPEN";
export const MODAL_PROFILE_UPLOAD_CLOSE = "MODAL_PROFILE_UPLOAD_CLOSE";
export const MODAL_PROFILE_UPLOAD_UPDATE = "MODAL_PROFILE_UPLOAD_UPDATE";
